//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated based on the Unicorn serialization items
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable InconsistentNaming
namespace <%= solutionX %>.<%= moduleTypeX %>.<%= moduleNameX %>.Models
{
    using Sitecore.Data;
    using System.CodeDom.Compiler;
}
